export const barPageData = {
    data: {
        bar: {
            name: "Speakeasy",
            description: "To enjoy life the easy way",
            contents: {
                Drink: {
                    DrinkTitle: "OUR STORY",
                    AboutUsText:
                        "Koseur has been a beacon for the community of Greenwich Village since it opened its doors in 1915. Now a registered New York City landmark, this modest meeting house has always attracted people from all walks of life: famous actors, writers, and musicians, to the down-at-heel of the beatnik generation, all of whom have found solace in its relaxed and unpretentious environs. A place where a cup of espresso, a warm smile or a friendly embrace epitomized life’s simple pleasures.",
                },
                BgText: "BRING ME KOSEUR",
                AboutUs: {
                    AboutUsText:
                        "A bar, café and Bar&Champagne, all in one. Thousands of stories, thousands of possibilities; the atmosphere, that intimacy, that light. The picture windows, look and be seen; watch life pass by or immerse yourself in it; enjoy the hustle and bustle of a Gijón that was always modern, independent, bourgeois, sophisticated and joyful: the little New York, the little London… the Great Gijón.",
                    AboutUsTitle: [
                        "Bar & Champagne",
                        "A new bar concept by Koseur",
                    ],
                },
            },
            images: [
                {
                    name: "background.jpeg",
                    formats: {
                        large: {
                            ext: ".jpeg",
                            url: "/uploads/large_background_d4f876fe1d.jpeg",
                            hash: "large_background_d4f876fe1d",
                            mime: "image/jpeg",
                            name: "large_background.jpeg",
                            path: null,
                            size: 115.7,
                            width: 1000,
                            height: 667,
                        },
                        small: {
                            ext: ".jpeg",
                            url: "/uploads/small_background_d4f876fe1d.jpeg",
                            hash: "small_background_d4f876fe1d",
                            mime: "image/jpeg",
                            name: "small_background.jpeg",
                            path: null,
                            size: 30.34,
                            width: 500,
                            height: 333,
                        },
                        medium: {
                            ext: ".jpeg",
                            url: "/uploads/medium_background_d4f876fe1d.jpeg",
                            hash: "medium_background_d4f876fe1d",
                            mime: "image/jpeg",
                            name: "medium_background.jpeg",
                            path: null,
                            size: 65.04,
                            width: 750,
                            height: 500,
                        },
                        thumbnail: {
                            ext: ".jpeg",
                            url: "/uploads/thumbnail_background_d4f876fe1d.jpeg",
                            hash: "thumbnail_background_d4f876fe1d",
                            mime: "image/jpeg",
                            name: "thumbnail_background.jpeg",
                            path: null,
                            size: 8.21,
                            width: 234,
                            height: 156,
                        },
                    },
                },
                {
                    name: "bartender.jpg",
                    formats: {
                        large: {
                            ext: ".jpg",
                            url: "/uploads/large_bartender_1a046982c7.jpg",
                            hash: "large_bartender_1a046982c7",
                            mime: "image/jpeg",
                            name: "large_bartender.jpg",
                            path: null,
                            size: 53.94,
                            width: 667,
                            height: 1000,
                        },
                        small: {
                            ext: ".jpg",
                            url: "/uploads/small_bartender_1a046982c7.jpg",
                            hash: "small_bartender_1a046982c7",
                            mime: "image/jpeg",
                            name: "small_bartender.jpg",
                            path: null,
                            size: 19.21,
                            width: 333,
                            height: 500,
                        },
                        medium: {
                            ext: ".jpg",
                            url: "/uploads/medium_bartender_1a046982c7.jpg",
                            hash: "medium_bartender_1a046982c7",
                            mime: "image/jpeg",
                            name: "medium_bartender.jpg",
                            path: null,
                            size: 35.37,
                            width: 500,
                            height: 750,
                        },
                        thumbnail: {
                            ext: ".jpg",
                            url: "/uploads/thumbnail_bartender_1a046982c7.jpg",
                            hash: "thumbnail_bartender_1a046982c7",
                            mime: "image/jpeg",
                            name: "thumbnail_bartender.jpg",
                            path: null,
                            size: 3.5,
                            width: 104,
                            height: 156,
                        },
                    },
                },
                {
                    name: "drink_1.jpg",
                    formats: {
                        large: {
                            ext: ".jpg",
                            url: "/uploads/large_drink_1_bfe77321e9.jpg",
                            hash: "large_drink_1_bfe77321e9",
                            mime: "image/jpeg",
                            name: "large_drink_1.jpg",
                            path: null,
                            size: 103.22,
                            width: 686,
                            height: 1000,
                        },
                        small: {
                            ext: ".jpg",
                            url: "/uploads/small_drink_1_bfe77321e9.jpg",
                            hash: "small_drink_1_bfe77321e9",
                            mime: "image/jpeg",
                            name: "small_drink_1.jpg",
                            path: null,
                            size: 24.2,
                            width: 343,
                            height: 500,
                        },
                        medium: {
                            ext: ".jpg",
                            url: "/uploads/medium_drink_1_bfe77321e9.jpg",
                            hash: "medium_drink_1_bfe77321e9",
                            mime: "image/jpeg",
                            name: "medium_drink_1.jpg",
                            path: null,
                            size: 58.96,
                            width: 515,
                            height: 750,
                        },
                        thumbnail: {
                            ext: ".jpg",
                            url: "/uploads/thumbnail_drink_1_bfe77321e9.jpg",
                            hash: "thumbnail_drink_1_bfe77321e9",
                            mime: "image/jpeg",
                            name: "thumbnail_drink_1.jpg",
                            path: null,
                            size: 3,
                            width: 107,
                            height: 156,
                        },
                    },
                },
            ],
            drinks: [
                {
                    id: "2",
                    name: "BOOZE and HOOCH",
                    ingredients: null,
                    images: [
                        {
                            formats: {
                                large: {
                                    ext: ".jpg",
                                    url: "/uploads/large_drink_2_0f51bcfbbc.jpg",
                                    hash: "large_drink_2_0f51bcfbbc",
                                    mime: "image/jpeg",
                                    name: "large_drink_2.jpg",
                                    path: null,
                                    size: 42.24,
                                    width: 1000,
                                    height: 667,
                                },
                                small: {
                                    ext: ".jpg",
                                    url: "/uploads/small_drink_2_0f51bcfbbc.jpg",
                                    hash: "small_drink_2_0f51bcfbbc",
                                    mime: "image/jpeg",
                                    name: "small_drink_2.jpg",
                                    path: null,
                                    size: 15.31,
                                    width: 500,
                                    height: 333,
                                },
                                medium: {
                                    ext: ".jpg",
                                    url: "/uploads/medium_drink_2_0f51bcfbbc.jpg",
                                    hash: "medium_drink_2_0f51bcfbbc",
                                    mime: "image/jpeg",
                                    name: "medium_drink_2.jpg",
                                    path: null,
                                    size: 27.77,
                                    width: 750,
                                    height: 500,
                                },
                                thumbnail: {
                                    ext: ".jpg",
                                    url: "/uploads/thumbnail_drink_2_0f51bcfbbc.jpg",
                                    hash: "thumbnail_drink_2_0f51bcfbbc",
                                    mime: "image/jpeg",
                                    name: "thumbnail_drink_2.jpg",
                                    path: null,
                                    size: 5.3,
                                    width: 234,
                                    height: 156,
                                },
                            },
                        },
                    ],
                },
                {
                    id: "3",
                    name: "Fall in Love with The Moon",
                    ingredients: null,
                    images: [
                        {
                            formats: {
                                large: {
                                    ext: ".jpg",
                                    url: "/uploads/large_drink_3_62bfaf3ed9.jpg",
                                    hash: "large_drink_3_62bfaf3ed9",
                                    mime: "image/jpeg",
                                    name: "large_drink_3.jpg",
                                    path: null,
                                    size: 45.32,
                                    width: 1000,
                                    height: 667,
                                },
                                small: {
                                    ext: ".jpg",
                                    url: "/uploads/small_drink_3_62bfaf3ed9.jpg",
                                    hash: "small_drink_3_62bfaf3ed9",
                                    mime: "image/jpeg",
                                    name: "small_drink_3.jpg",
                                    path: null,
                                    size: 15.13,
                                    width: 500,
                                    height: 333,
                                },
                                medium: {
                                    ext: ".jpg",
                                    url: "/uploads/medium_drink_3_62bfaf3ed9.jpg",
                                    hash: "medium_drink_3_62bfaf3ed9",
                                    mime: "image/jpeg",
                                    name: "medium_drink_3.jpg",
                                    path: null,
                                    size: 29.14,
                                    width: 750,
                                    height: 500,
                                },
                                thumbnail: {
                                    ext: ".jpg",
                                    url: "/uploads/thumbnail_drink_3_62bfaf3ed9.jpg",
                                    hash: "thumbnail_drink_3_62bfaf3ed9",
                                    mime: "image/jpeg",
                                    name: "thumbnail_drink_3.jpg",
                                    path: null,
                                    size: 5.01,
                                    width: 234,
                                    height: 156,
                                },
                            },
                        },
                    ],
                },
                {
                    id: "4",
                    name: "HEAVEN in HELL",
                    ingredients: null,
                    images: [
                        {
                            formats: {
                                large: {
                                    ext: ".jpg",
                                    url: "/uploads/large_drink_4_2c96e91d19.jpg",
                                    hash: "large_drink_4_2c96e91d19",
                                    mime: "image/jpeg",
                                    name: "large_drink_4.jpg",
                                    path: null,
                                    size: 43.73,
                                    width: 1000,
                                    height: 667,
                                },
                                small: {
                                    ext: ".jpg",
                                    url: "/uploads/small_drink_4_2c96e91d19.jpg",
                                    hash: "small_drink_4_2c96e91d19",
                                    mime: "image/jpeg",
                                    name: "small_drink_4.jpg",
                                    path: null,
                                    size: 15.65,
                                    width: 500,
                                    height: 333,
                                },
                                medium: {
                                    ext: ".jpg",
                                    url: "/uploads/medium_drink_4_2c96e91d19.jpg",
                                    hash: "medium_drink_4_2c96e91d19",
                                    mime: "image/jpeg",
                                    name: "medium_drink_4.jpg",
                                    path: null,
                                    size: 28.51,
                                    width: 750,
                                    height: 500,
                                },
                                thumbnail: {
                                    ext: ".jpg",
                                    url: "/uploads/thumbnail_drink_4_2c96e91d19.jpg",
                                    hash: "thumbnail_drink_4_2c96e91d19",
                                    mime: "image/jpeg",
                                    name: "thumbnail_drink_4.jpg",
                                    path: null,
                                    size: 5.54,
                                    width: 234,
                                    height: 156,
                                },
                            },
                        },
                    ],
                },
                {
                    id: "5",
                    name: "Apple Martini",
                    ingredients: [
                        "vodka",
                        "apple juice",
                        "apple cider",
                        "apple liqueur",
                        "apple brandy",
                    ],
                    images: [
                        {
                            formats: {
                                large: {
                                    ext: ".png",
                                    url: "/uploads/large_apple_martini_c4f54c24cb.png",
                                    hash: "large_apple_martini_c4f54c24cb",
                                    mime: "image/png",
                                    name: "large_apple-martini.png",
                                    path: null,
                                    size: 1260.06,
                                    width: 1000,
                                    height: 667,
                                },
                                small: {
                                    ext: ".png",
                                    url: "/uploads/small_apple_martini_c4f54c24cb.png",
                                    hash: "small_apple_martini_c4f54c24cb",
                                    mime: "image/png",
                                    name: "small_apple-martini.png",
                                    path: null,
                                    size: 351.93,
                                    width: 500,
                                    height: 333,
                                },
                                medium: {
                                    ext: ".png",
                                    url: "/uploads/medium_apple_martini_c4f54c24cb.png",
                                    hash: "medium_apple_martini_c4f54c24cb",
                                    mime: "image/png",
                                    name: "medium_apple-martini.png",
                                    path: null,
                                    size: 742.59,
                                    width: 750,
                                    height: 500,
                                },
                                thumbnail: {
                                    ext: ".png",
                                    url: "/uploads/thumbnail_apple_martini_c4f54c24cb.png",
                                    hash: "thumbnail_apple_martini_c4f54c24cb",
                                    mime: "image/png",
                                    name: "thumbnail_apple-martini.png",
                                    path: null,
                                    size: 87.75,
                                    width: 234,
                                    height: 156,
                                },
                            },
                        },
                    ],
                },
                {
                    id: "6",
                    name: "Long Island Ice Tea",
                    ingredients: [
                        "vodka",
                        "tequila",
                        "light rum",
                        "triple sec",
                        "gin",
                        "cola",
                    ],
                    images: [],
                },
                {
                    id: "7",
                    name: "Sazerac",
                    ingredients: [
                        "whiskey",
                        "simple syrup",
                        "dashes Peychaud's bitters",
                        "Absinthe",
                    ],
                    images: [
                        {
                            formats: {
                                large: {
                                    ext: ".png",
                                    url: "/uploads/large_sazerac_29d0801213.png",
                                    hash: "large_sazerac_29d0801213",
                                    mime: "image/png",
                                    name: "large_sazerac.png",
                                    path: null,
                                    size: 1164.21,
                                    width: 667,
                                    height: 1000,
                                },
                                small: {
                                    ext: ".png",
                                    url: "/uploads/small_sazerac_29d0801213.png",
                                    hash: "small_sazerac_29d0801213",
                                    mime: "image/png",
                                    name: "small_sazerac.png",
                                    path: null,
                                    size: 321.83,
                                    width: 333,
                                    height: 500,
                                },
                                medium: {
                                    ext: ".png",
                                    url: "/uploads/medium_sazerac_29d0801213.png",
                                    hash: "medium_sazerac_29d0801213",
                                    mime: "image/png",
                                    name: "medium_sazerac.png",
                                    path: null,
                                    size: 684.16,
                                    width: 500,
                                    height: 750,
                                },
                                thumbnail: {
                                    ext: ".png",
                                    url: "/uploads/thumbnail_sazerac_29d0801213.png",
                                    hash: "thumbnail_sazerac_29d0801213",
                                    mime: "image/png",
                                    name: "thumbnail_sazerac.png",
                                    path: null,
                                    size: 35.74,
                                    width: 104,
                                    height: 156,
                                },
                            },
                        },
                    ],
                },
            ],
        },
    },
};
