export const homePageData = {
    data: {
        categories: [
            {
                name: "Recommended for you",
                description: "Best bars based on your locale and preferences",
                bars: [
                    {
                        name: "Speakeasy",
                        logo: {
                            formats: {
                                thumbnail: {
                                    ext: ".png",
                                    url: "/uploads/thumbnail_186511985_300271234936856_2996271306666290717_n_a7a36c91d8.png",
                                    hash: "thumbnail_186511985_300271234936856_2996271306666290717_n_a7a36c91d8",
                                    mime: "image/png",
                                    name: "thumbnail_186511985_300271234936856_2996271306666290717_n.png",
                                    path: null,
                                    size: 13.43,
                                    width: 142,
                                    height: 156,
                                },
                            },
                        },
                        description: "To enjoy life the easy way",
                        images: [
                            {
                                formats: {
                                    large: {
                                        ext: ".jpeg",
                                        url: "/uploads/large_background_d4f876fe1d.jpeg",
                                        hash: "large_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "large_background.jpeg",
                                        path: null,
                                        size: 115.7,
                                        width: 1000,
                                        height: 667,
                                    },
                                    small: {
                                        ext: ".jpeg",
                                        url: "/uploads/small_background_d4f876fe1d.jpeg",
                                        hash: "small_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "small_background.jpeg",
                                        path: null,
                                        size: 30.34,
                                        width: 500,
                                        height: 333,
                                    },
                                    medium: {
                                        ext: ".jpeg",
                                        url: "/uploads/medium_background_d4f876fe1d.jpeg",
                                        hash: "medium_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "medium_background.jpeg",
                                        path: null,
                                        size: 65.04,
                                        width: 750,
                                        height: 500,
                                    },
                                    thumbnail: {
                                        ext: ".jpeg",
                                        url: "/uploads/thumbnail_background_d4f876fe1d.jpeg",
                                        hash: "thumbnail_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "thumbnail_background.jpeg",
                                        path: null,
                                        size: 8.21,
                                        width: 234,
                                        height: 156,
                                    },
                                },
                                alternativeText: "",
                                size: 257.4,
                            },
                            {
                                formats: {
                                    large: {
                                        ext: ".jpg",
                                        url: "/uploads/large_bartender_1a046982c7.jpg",
                                        hash: "large_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "large_bartender.jpg",
                                        path: null,
                                        size: 53.94,
                                        width: 667,
                                        height: 1000,
                                    },
                                    small: {
                                        ext: ".jpg",
                                        url: "/uploads/small_bartender_1a046982c7.jpg",
                                        hash: "small_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "small_bartender.jpg",
                                        path: null,
                                        size: 19.21,
                                        width: 333,
                                        height: 500,
                                    },
                                    medium: {
                                        ext: ".jpg",
                                        url: "/uploads/medium_bartender_1a046982c7.jpg",
                                        hash: "medium_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "medium_bartender.jpg",
                                        path: null,
                                        size: 35.37,
                                        width: 500,
                                        height: 750,
                                    },
                                    thumbnail: {
                                        ext: ".jpg",
                                        url: "/uploads/thumbnail_bartender_1a046982c7.jpg",
                                        hash: "thumbnail_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "thumbnail_bartender.jpg",
                                        path: null,
                                        size: 3.5,
                                        width: 104,
                                        height: 156,
                                    },
                                },
                                alternativeText: "",
                                size: 660.82,
                            },
                            {
                                formats: {
                                    large: {
                                        ext: ".jpg",
                                        url: "/uploads/large_drink_1_bfe77321e9.jpg",
                                        hash: "large_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "large_drink_1.jpg",
                                        path: null,
                                        size: 103.22,
                                        width: 686,
                                        height: 1000,
                                    },
                                    small: {
                                        ext: ".jpg",
                                        url: "/uploads/small_drink_1_bfe77321e9.jpg",
                                        hash: "small_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "small_drink_1.jpg",
                                        path: null,
                                        size: 24.2,
                                        width: 343,
                                        height: 500,
                                    },
                                    medium: {
                                        ext: ".jpg",
                                        url: "/uploads/medium_drink_1_bfe77321e9.jpg",
                                        hash: "medium_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "medium_drink_1.jpg",
                                        path: null,
                                        size: 58.96,
                                        width: 515,
                                        height: 750,
                                    },
                                    thumbnail: {
                                        ext: ".jpg",
                                        url: "/uploads/thumbnail_drink_1_bfe77321e9.jpg",
                                        hash: "thumbnail_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "thumbnail_drink_1.jpg",
                                        path: null,
                                        size: 3,
                                        width: 107,
                                        height: 156,
                                    },
                                },
                                alternativeText: "",
                                size: 2509.89,
                            },
                        ],
                    },
                ],
            },
            {
                name: "In Hanoi",
                description: "Straight in the capital of Vietnam",
                bars: [
                    {
                        name: "Speakeasy",
                        logo: {
                            formats: {
                                thumbnail: {
                                    ext: ".png",
                                    url: "/uploads/thumbnail_186511985_300271234936856_2996271306666290717_n_a7a36c91d8.png",
                                    hash: "thumbnail_186511985_300271234936856_2996271306666290717_n_a7a36c91d8",
                                    mime: "image/png",
                                    name: "thumbnail_186511985_300271234936856_2996271306666290717_n.png",
                                    path: null,
                                    size: 13.43,
                                    width: 142,
                                    height: 156,
                                },
                            },
                        },
                        description: "To enjoy life the easy way",
                        images: [
                            {
                                formats: {
                                    large: {
                                        ext: ".jpeg",
                                        url: "/uploads/large_background_d4f876fe1d.jpeg",
                                        hash: "large_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "large_background.jpeg",
                                        path: null,
                                        size: 115.7,
                                        width: 1000,
                                        height: 667,
                                    },
                                    small: {
                                        ext: ".jpeg",
                                        url: "/uploads/small_background_d4f876fe1d.jpeg",
                                        hash: "small_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "small_background.jpeg",
                                        path: null,
                                        size: 30.34,
                                        width: 500,
                                        height: 333,
                                    },
                                    medium: {
                                        ext: ".jpeg",
                                        url: "/uploads/medium_background_d4f876fe1d.jpeg",
                                        hash: "medium_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "medium_background.jpeg",
                                        path: null,
                                        size: 65.04,
                                        width: 750,
                                        height: 500,
                                    },
                                    thumbnail: {
                                        ext: ".jpeg",
                                        url: "/uploads/thumbnail_background_d4f876fe1d.jpeg",
                                        hash: "thumbnail_background_d4f876fe1d",
                                        mime: "image/jpeg",
                                        name: "thumbnail_background.jpeg",
                                        path: null,
                                        size: 8.21,
                                        width: 234,
                                        height: 156,
                                    },
                                },
                                alternativeText: "",
                                size: 257.4,
                            },
                            {
                                formats: {
                                    large: {
                                        ext: ".jpg",
                                        url: "/uploads/large_bartender_1a046982c7.jpg",
                                        hash: "large_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "large_bartender.jpg",
                                        path: null,
                                        size: 53.94,
                                        width: 667,
                                        height: 1000,
                                    },
                                    small: {
                                        ext: ".jpg",
                                        url: "/uploads/small_bartender_1a046982c7.jpg",
                                        hash: "small_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "small_bartender.jpg",
                                        path: null,
                                        size: 19.21,
                                        width: 333,
                                        height: 500,
                                    },
                                    medium: {
                                        ext: ".jpg",
                                        url: "/uploads/medium_bartender_1a046982c7.jpg",
                                        hash: "medium_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "medium_bartender.jpg",
                                        path: null,
                                        size: 35.37,
                                        width: 500,
                                        height: 750,
                                    },
                                    thumbnail: {
                                        ext: ".jpg",
                                        url: "/uploads/thumbnail_bartender_1a046982c7.jpg",
                                        hash: "thumbnail_bartender_1a046982c7",
                                        mime: "image/jpeg",
                                        name: "thumbnail_bartender.jpg",
                                        path: null,
                                        size: 3.5,
                                        width: 104,
                                        height: 156,
                                    },
                                },
                                alternativeText: "",
                                size: 660.82,
                            },
                            {
                                formats: {
                                    large: {
                                        ext: ".jpg",
                                        url: "/uploads/large_drink_1_bfe77321e9.jpg",
                                        hash: "large_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "large_drink_1.jpg",
                                        path: null,
                                        size: 103.22,
                                        width: 686,
                                        height: 1000,
                                    },
                                    small: {
                                        ext: ".jpg",
                                        url: "/uploads/small_drink_1_bfe77321e9.jpg",
                                        hash: "small_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "small_drink_1.jpg",
                                        path: null,
                                        size: 24.2,
                                        width: 343,
                                        height: 500,
                                    },
                                    medium: {
                                        ext: ".jpg",
                                        url: "/uploads/medium_drink_1_bfe77321e9.jpg",
                                        hash: "medium_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "medium_drink_1.jpg",
                                        path: null,
                                        size: 58.96,
                                        width: 515,
                                        height: 750,
                                    },
                                    thumbnail: {
                                        ext: ".jpg",
                                        url: "/uploads/thumbnail_drink_1_bfe77321e9.jpg",
                                        hash: "thumbnail_drink_1_bfe77321e9",
                                        mime: "image/jpeg",
                                        name: "thumbnail_drink_1.jpg",
                                        path: null,
                                        size: 3,
                                        width: 107,
                                        height: 156,
                                    },
                                },
                                alternativeText: "",
                                size: 2509.89,
                            },
                        ],
                    },
                ],
            },
        ],
    },
};
